#!/bin/bash

# Buildx Builder
docker buildx create --name "${BUILDX_NAME:-tele-aria2}" || echo
docker buildx use "${BUILDX_NAME:-tele-aria2}"

docker buildx build \
	-f Dockerfile \
       -t leolitaly/tele-aria2:latest \
	--platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 . --push \

rc=$?
docker buildx rm "${BUILDX_NAME:-tele-aria2}"
echo -e "${BLUE}❯ ${GREEN}Multiarch build Complete${RESET}"
exit $rc
